# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Get latest version of Hugo
        id: hugo_version
        run: echo "::set-output name=latest::$(gh release list --limit 1 --repo gohugoio/hugo | awk '{print substr($1, 2)}')"

      - name: Update Dockerfile
        run: sed -i -r "s/ENV HUGO_VERSION=\S*/ENV HUGO_VERSION=${{ steps.hugo_version.outputs.latest }}/" .gitpod.Dockerfile

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v4.0.2
        with:
          branch: hugo-upgrade/v${{ steps.hugo_version.outputs.latest }}
          commit-message: Upgrade Hugo to ${{ steps.hugo_version.outputs.latest }}
          delete-branch: true
          labels: dependencies
          title: Upgrade Hugo to ${{ steps.hugo_version.outputs.latest }}
