# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

jobs:
  upgrade:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Get latest version of Hugo
        id: hugo_version
        run: echo "::set-output name=latest::$(gh release view --repo gohugoio/hugo --json tagName | jq -r '.tagName')"

      - name: Update Dockerfile
        run: sed -i -r "s/ENV HUGO_VERSION=\S*/ENV HUGO_VERSION=${{ steps.hugo_version.outputs.latest }}/" .gitpod.Dockerfile

      - name: Get release note
        id: release_note
        run: echo "::set-output name=latest::$(gh release view --repo gohugoio/hugo --json body | jq -r '.body' | sed 's/@/@<!-- -->/g')"

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v4.0.2
        with:
          author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
          body: <details><summary>Release Note</summary>${{ steps.release_note.outputs.latest }}</details>
          branch: upgrade-hugo/v${{ steps.hugo_version.outputs.latest }}
          commit-message: Upgrade Hugo to ${{ steps.hugo_version.outputs.latest }}
          delete-branch: true
          labels: dependencies
          title: Upgrade Hugo to ${{ steps.hugo_version.outputs.latest }}